### ISSUE TITLE
Multiple pipelines with the same name

### ISSUE THREAD

**Issue by mbpolan** [Azure/pipelines#28]
I have a GitHub Action that should trigger an Azure DevOps pipeline. In my project, I have multiple pipelines that have the same name, but are grouped under different folders by convention. For example:

```
+ my-app-1
  - deploy
+ my-app-2
  - deploy
```

In the above, `my-app-1` and `my-app-2` are folders corresponding to different repositories, and our standards are to have a `deploy` pipeline for each repository. I would like to trigger specific `deploy` pipelines using a GitHub Action.

```
- name: Azure Pipelines Action
  uses: Azure/pipelines@v1
  with:
    azure-devops-project-url: https://dev.azure.com/organization/project
    azure-pipeline-name: 'deploy'       # this is in question
    azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
```

How would I configure the action to trigger the `my-app-1/deploy` pipeline specifically?

In the above snippet, if I specify `deploy` by itself, I get an error:
`More than 1 Pipeline named "deploy" found in project "project"`

If I try to prefix this with either `my-app-1/deploy` or `my-app-1\deploy`, I get a different error:
`Failed request: (401)`

The only way I'm able to get this to work is if I give each pipeline a unique name, but I'd prefer not to have to break my existing conventions to do this.
