### ISSUE TITLE
Unable to pass variables to Azure Pipeline

### ISSUE THREAD

**Issue by alexrster** [Azure/pipelines#40]
Hi guys,

I'm trying to use 'azure-pipelines-variables' parameters to pass some values to Azure Pipeline. Azure Pipeline is getting triggered but variables are not gets passed.

There is a warning in the GitHub Actions log:

```
Warning: Unexpected input(s) 'azure-pipeline-variables', valid inputs are ['azure-devops-project-url', 'azure-pipeline-name', 'azure-devops-token']
Run Azure/pipelines@v1
  with:
    azure-devops-project-url: https://dev.azure.com/qxzone/ContactPoint%20IP%20phone
    azure-pipeline-name: Release
    azure-pipeline-variables: { "cp.CoreVersion": "1.13.1" }
    azure-devops-token: ***
  env:
    CoreVersion: 1.13.1
```

GitHub Workflow (part):

```
  release:
    runs-on: ubuntu-18.04

    steps:
    - name: Trigger Azure Release Pipeline
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/qxzone/ContactPoint%20IP%20phone'
        azure-pipeline-name: 'Release'
        azure-pipeline-variables: '{ "cp.CoreVersion": "${{ env.CoreVersion }}" }'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
```

Runner options: ubuntu-latest, ubuntu-18.04
