### ISSUE TITLE
[Question] Multi line Pipeline Variables

### ISSUE THREAD

**Issue by obeyda** [Azure/pipelines#65]
when trying to split the pipeline variables on multiple lines I am getting this: 
``` Could not cast or convert from System.String to System.Collections.Generic.IDictionary`2[System.String,System.String].```

      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          ...
          azure-pipeline-variables: >
            '{
             "v1": "1",
             "v2": "2", 
             "v3": true 
              }'

**Comment by asilverman** [comment]
@obeyda I think that to get this to work you want to specify it as follows (without single quotes):
```yaml
 - name: Azure Pipelines Action
    uses: Azure/pipelines@v1.2
    with:
      ...
      azure-pipeline-variables: >
        {
         "v1": "1",
         "v2": "2", 
         "v3": true 
         }
```
**notice how the single quotes are removed**
