### ISSUE TITLE
[Bug] Sample in README needs updating

### ISSUE THREAD

**Issue by keifgwinn** [Azure/pipelines#68]
Sample provided on the README gives an action that won't operate correctly.

```

- uses: Azure/pipelines@v1
  with:
    azure-devops-project-url: 'https://dev.azure.com/organization/project-name'
    azure-pipeline-name: 'pipeline-name' # name of the Azure pipeline to be triggered
    azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
    azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
```

however if you use 'azure-pipeline-variables' in your own action you get 

`Warning: Unexpected input(s) 'azure-pipeline-variables', valid inputs are ['azure-devops-project-url', 'azure-pipeline-name', 'azure-devops-token']`

So sample should read 

```
- uses: Azure/pipelines@v1.2
  with:
    azure-devops-project-url: 'https://dev.azure.com/organization/project-name'
    azure-pipeline-name: 'pipeline-name' # name of the Azure pipeline to be triggered
    azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
    azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
```

Encountered on https://github.com/3drepo/3drepo.io/issues/3475
