### ISSUE TITLE
[Bug] Deprecations

### ISSUE THREAD

**Issue by saliceti** [Azure/pipelines#70]
This should be updated or the action will stop working

## node12
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Azure/pipelines
```

## set-output
```
The `set-output` command is deprecated 
and will be disabled soon. Please upgrade to using Environment Files. 
For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by craigbroadman** [comment]
@tjcorr, @keifgwinn, @Josh-01 - is there any idea when this will be resolved as node 12 is deprecated?

**Comment by marcus1aleksand** [comment]
Not long ago, I ran into the same problem and noticed that this module wasn't being maintained so I forked it and fixed in the forked repo maintained by me. Now, it can be consumable in ver 1.4. I can also push something similar to a Liatrio repo. Here is the link for the fix: https://github.com/marcus1aleksand/adopipelines

Here is an use example:
```
- uses: marcus1aleksand/adopipelines@v1.4
  with:
    azure-devops-project-url: 'https://dev.azure.com/organization/project-name'
    azure-pipeline-name: 'pipeline-name' # name of the Azure pipeline to be triggered
    azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
    azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
```
