### ISSUE TITLE
[Bug] Does not allow to parameterize the repository resource ref attribute when the resources are inside an extended template.

### ISSUE THREAD

**Issue by MarkKharitonov** [Azure/pipelines#82]
Consider the following simple pipeline consisting of two small YAML files:
**run.yaml**
```
trigger: none

extends:
  template: do-run.yaml
  parameters:
    master_branch: publish_test
```
**do-run.yaml**
```
parameters:
  - name: master_branch
    default: master

resources:
  repositories:
    - repository: chip_aks_helmcharts
      type: git
      name: CHIP/chip_aks_helmcharts
      ref: ${{ parameters.master_branch }}
      # https://dev.azure.com/CeridianHosting/CHIP/_git/chip_aks_helmcharts

steps: []
```
The pipeline link is https://dev.azure.com/CeridianHosting/CHIP/_build?definitionId=695

The code is on the `test` branch. Trying to run the pipeline results in 
```
/test_yaml_extends/run.yaml: Internal error reading the template. Expected a scalar, a sequence, or a mapping
```
![image](https://user-images.githubusercontent.com/489792/236521443-227dca19-d249-4ce3-89b5-fe92286815e1.png)

1. If I replace `ref: ${{ parameters.master_branch }}` with `ref: publish_test`, then queuing the build works fine. (this is the master branch)
2. If I inline the `do-run.yaml`, i.e. not use the YAML extension feature (branch no_extended_yaml) then I can queue the build just fine and modify the `ref` attribute.

So it seems that the parametrization of the `ref` attribute is not possible when the resources are declared inside the extended YAML.
