### ISSUE TITLE
[Bug] Could not queue the build because there were validation errors or warnings.

### ISSUE THREAD

**Issue by priscofarina** [Azure/pipelines#95]
I am trying to use the new version:    

```
- uses: Azure/pipelines@v1.2
  with:
    azure-devops-project-url: 'https://dev.azure.com/organization/project-name'
    azure-pipeline-name: 'pipeline-name' # name of the Azure pipeline to be triggered
    azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
    azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
```

but once I create the workflow in which I pass some variables I get the following message:

**Error: Could not queue the build because there were validation errors or warnings.**

Are those not supported yet?

Removing the following section from my workflow definition, the pipeline get triggered.

`    azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
`
